version: '3.8'
services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - webapp

  webapp:
    build: ./webapp
    environment:
      - REDIS_HOST=redis
      - DEPENDS_ON=redis

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
